language: r
sudo: false
cache: packages

r: bioc-devel

env:
  global: _R_CHECK_FORCE_SUGGESTS_=FALSE

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
